title: Resume
author: Sameh Selim
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is Sameh Selim Resume
  
# social links
twitter_username: sskarim
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
